### ISSUE TITLE
Use symcrypt for crypto operations

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#1681]
Replace other crates with [`symcrypt`](https://docs.rs/symcrypt).

**Comment by demoray** [comment]
I hope this is an optional feature, as the rust symcrypt has limited OS support at this time and does not include static linking at this time (required for musl related builds).

**Comment by heaths** [comment]
This won't be ready for some time.

**Comment by RickWinter** [comment]
# Issue #1681: Use symcrypt for crypto operations

Replace other crypto crates with [`symcrypt`](https://docs.rs/symcrypt).

## Background

The Azure SDK for Rust currently uses `hmac`/`sha2` and `openssl` crates for cryptographic operations. Microsoft's [`symcrypt`](https://github.com/microsoft/rust-symcrypt) crate provides FIPS 140-2/140-3 certified cryptography. Migrating to `symcrypt` aligns the Rust SDK with Microsoft's security requirements.

## Current Crypto Usage

| Crate | File | Operation | Current Dependency |
|-------|------|-----------|--------------------|
| `azure_core` | `src/hmac.rs` | HMAC-SHA256 signing (Azure auth) | `hmac` + `sha2` (feature: `hmac_rust`) or `openssl` (feature: `hmac_openssl`) |
| `azure_identity` | `src/client_certificate_credential.rs` | X.509 cert parsing + JWT signing | `openssl` (feature: `client_certificate`) |

No other SDK crates (`azure_storage_*`, `azure_security_keyvault_*`, `azure_messaging_*`, `azure_core_amqp`) use crypto directly.

## SymCrypt Capabilities (v0.5.1)

| Algorithm | Supported | Needed |
|-----------|-----------|--------|
| HMAC-SHA256 | ✅ | ✅ `azure_core` auth signing |
| SHA-256/384/512 | ✅ | ✅ hashing |
| RSA sign/verify (PKCS#1, PSS, OAEP) | ✅ | ✅ JWT signing in `azure_identity` |
| ECDSA (P-256, P-384, P-521) | ✅ | ✅ JWT signing in `azure_identity` |
| AES-GCM/CBC | ✅ | ❌ not currently used |
| X.509 certificate parsing | ❌ | ⚠️ still needed for `client_certificate_credential` |
| Random bytes | ✅ (`symcrypt_random()`) | ❌ not currently used (repo uses `rand`) |

### Platform Support

| Target | Supported |
|--------|-----------|
| `x86_64-pc-windows-msvc` | ✅ |
| `aarch64-pc-windows-msvc` | ✅ |
| `x86_64-unknown-linux-gnu` | ✅ |
| `aarch64-unknown-linux-gnu` | ✅ |
| macOS | ❌ |
| musl (Alpine, etc.) | ❌ |

### Linking

- **Static linking** (default): Links to pre-built SymCrypt static library.
- **Dynamic linking** (`dynamic` feature): Links to system `symcrypt.dll` / `libsymcrypt.so`.

## Constraints & Risks

1. **No macOS or musl support** — `symcrypt` only targets Windows and Linux (glibc). This must remain behind a feature flag so developers on macOS and musl-based environments (Docker Alpine) can continue building.
2. **X.509 parsing not included** — `symcrypt` is a primitives library; it does not parse X.509 certificates. `azure_identity`'s `client_certificate_credential` will still need a cert-parsing crate (e.g., `x509-parser`, `rustls-pemfile`, or retain `openssl` for parsing only).
3. **System library dependency** — `symcrypt` requires the SymCrypt C library to be present at build time. CI/CD pipelines must install it.

## Implementation Plan

### Phase 1: `azure_core` — HMAC-SHA256 replacement

1. **Add `symcrypt` workspace dependency** in root `Cargo.toml`.
2. **Add `hmac_symcrypt` feature** to `azure_core/Cargo.toml`:
   ```toml
   [features]
   hmac_symcrypt = ["dep:symcrypt"]
   ```
3. **Add symcrypt HMAC implementation** in `azure_core/src/hmac.rs`:
   - Add a `#[cfg(feature = "hmac_symcrypt")]` block implementing `hmac_sha256()` using `symcrypt::hmac::HmacSha256State`.
   - Maintain the existing `hmac_rust` and `hmac_openssl` implementations.
   - Establish precedence: `hmac_symcrypt` > `hmac_openssl` > `hmac_rust`.
4. **Run existing HMAC test** (`test_hmac_sign`) with each feature flag to validate parity.

### Phase 2: `azure_identity` — JWT signing replacement

1. **Add `symcrypt` feature** to `azure_identity/Cargo.toml`:
   ```toml
   [features]
   client_certificate_symcrypt = ["dep:symcrypt", "dep:x509-parser"]
   ```
2. **Refactor `client_certificate_credential.rs`**:
   - Extract X.509 certificate parsing into a separate function. Use `x509-parser` (pure Rust) or keep `openssl` for parsing only.
   - Replace JWT signing (`openssl::sign::Signer`) with `symcrypt::rsa` or `symcrypt::ecc::ecdsa` depending on key type.
3. **Keep `client_certificate` feature** using `openssl` as a fallback for platforms without symcrypt.

### Phase 3: Feature flag defaults & documentation

1. **Set `hmac_symcrypt` as default** on supported platforms (Windows, Linux glibc) via target-specific defaults, or document how to opt in.
2. **Update `CONTRIBUTING.md`** with SymCrypt build prerequisites.
3. **Update CI pipelines** to install SymCrypt libraries and test with `hmac_symcrypt` feature enabled.

## Required Tests

### Unit Tests

| Test | Location | Description |
|------|----------|-------------|
| `test_hmac_sign_symcrypt` | `azure_core/src/hmac.rs` | Verify HMAC-SHA256 output matches existing test vector (`FFFF...FF` key) when using `hmac_symcrypt` feature. Must produce identical output to `hmac_rust` and `hmac_openssl` implementations. |
| `test_hmac_sign_parity` | `azure_core/src/hmac.rs` | Run all three HMAC backends against multiple test vectors (empty input, short input, long input, binary key) and assert identical base64 output. |
| `test_hmac_invalid_key` | `azure_core/src/hmac.rs` | Verify that an invalid (non-base64) key returns an appropriate error with `hmac_symcrypt`. |

### Integration Tests

| Test | Location | Description |
|------|----------|-------------|
| `test_certificate_credential_rsa_symcrypt` | `azure_identity/tests/` | Authenticate using an RSA client certificate with `client_certificate_symcrypt` feature. Verify token acquisition succeeds against a mock identity endpoint. |
| `test_certificate_credential_ec_symcrypt` | `azure_identity/tests/` | Same as above using an EC (P-256) client certificate. |
| `test_certificate_credential_pfx_symcrypt` | `azure_identity/tests/` | Test PFX/PKCS#12 certificate loading and signing via symcrypt. |

### CI Gate Tests

| Test | Pipeline Step | Description |
|------|---------------|-------------|
| Feature matrix build | `ci.yml` | Build `azure_core` with each HMAC feature individually (`hmac_rust`, `hmac_openssl`, `hmac_symcrypt`) and verify compilation succeeds. |
| Platform matrix | `ci.yml` | Verify `hmac_symcrypt` builds on Windows x86_64, Linux x86_64, and Linux ARM64. Verify graceful fallback (feature not enabled) on macOS. |
| No-default-features build | `ci.yml` | Build with `--no-default-features` to ensure symcrypt is fully optional. |

## Open Questions

- [ ] Should `hmac_symcrypt` become the default on supported platforms, or remain opt-in?
- [ ] For `azure_identity` cert parsing, prefer `x509-parser` (pure Rust, no system deps) or keep `openssl` for parsing while using `symcrypt` only for signing?
- [ ] What is the minimum `symcrypt` crate version to target? Current is 0.5.1 — should we wait for 1.0?
- [ ] How should CI provision the SymCrypt system library? Package manager, vendored binary, or build from source?

**Comment by heaths** [comment]
Removed `blocking-release` since this was in the backlog both for milestones and in the project. Not blocking if it's on the backlog.

This is one major reason why we have pluggability for HTTP and, by extension, TLS.

**Comment by heaths** [comment]
Given the research notes below, I don't think `rustls-pemfile` will be sufficient if we need to parse the subject, etc., which I believe we do.

---

### rustls-pemfile for X.509 certificate parsing in azure_identity

Based on the context in this thread and the full comment ([link](https://github.com/Azure/azure-sdk-for-rust/issues/1681#issuecomment-4078597878)), `azure_identity` currently requires X.509 certificate parsing for client certificate credential support. While `symcrypt` covers the required cryptographic primitives (RSA/ECDSA signing), it does **not** provide X.509 parsing capabilities. The project already considered other Rust-native crates for certificate parsing, such as `x509-parser` and `rustls-pemfile`, or retaining `openssl` for parsing only.

The [`rustls-pemfile`](https://docs.rs/rustls-pemfile/2.2.0) crate provides functions for parsing PEM-encoded data from input streams and extracting certificates and keys. However, its focus is limited to basic PEM file parsing (extracting DER-encoded blobs), not full X.509 parsing:

- It can extract certificate/key entries from a PEM stream (e.g., as returned from reading a `.pem` file)
- It does **not** parse the contents of an X.509 certificate (e.g., subject, validity, extensions, public key, etc.)

This means `rustls-pemfile` is sufficient **only if** you want to extract DER-encoded blobs to hand off to another library (such as a cryptography backend that accepts DER directly). However, if you need to inspect certificate fields or validate properties of the X.509 certificate itself (issuer, validity, etc.), additional parsing logic or a more sophisticated crate like [`x509-parser`](https://docs.rs/x509-parser) is necessary.

**Summary:**
- If azure_identity only needs to extract certificate/key blobs in DER and pass them to cryptographic routines, `rustls-pemfile` can work.
- If azure_identity needs to parse or validate certificate fields, you'll need a full X.509 parser such as `x509-parser` or continue using `openssl` for parsing.

Let me know if a deeper comparison or code sample is needed!

**Comment by heaths** [comment]
Putting on backlog until we have solid demand. `openssl` is approved by the Microsoft Cryptography Board, so I'm not convinced there's much _need_ currently.
