### ISSUE TITLE
Support crates within service directories

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#1702]
We need to be able to support multiple crates within a service directory for some services like Key Vault, Storage, and possibly Cosmos. The unofficial source puts them side by side but having consistent service directories is handy for checking across languages, and since we're migrating to TypeSpec, we also can't always merge e.g., Cognitive Services, or separate e.g., Key Vault, TypeSpec projects into separate crates.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-rust/issues/1703
- [x] Code emitter can generate crates under a service directory instead of directly therein.
- [x] CI knows to look deeper for some/all crates.
```

Should we just always nest crates then? Having a variety just makes maintenance and accessibility harder. For single crates it may be redundant, but we could still argue that even those could eventually have multiple crates e.g.,

* `sdk/core/azure_core`
* `sdk/core/azure_derive`

**Comment by heaths** [comment]
Already supported now.
