### ISSUE TITLE
migrate SDKs to `azure_core::error::Error`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#771]
Three months ago, in late February, #625 was merged. It added `azure_core::error::Error` and migrated a few SDKs. Earlier this week, #766 was merged to migrate all of the generated services. These still need to be migrated.

  - [x] sdk/core HttpClient::execute_request2 @cataggar #779
  - [x] sdk/identity @cataggar #781
  - [x] sdk/security_keyvault @johnbatty #782 
  - [x] sdk/data_tables @johnbatty #805
  - [x] sdk/device_update @mfrw #794
  - [x] sdk/iot_hub @cataggar #801 
  - [x] sdk/storage @johnbatty #792
  - [x] sdk/storage_blobs @rickrain #794
  - [x] sdk/storage_datalake @roeap #795
  - [x] sdk/storage_queues @johnbatty #800 
  - [x] sdk/messaging_servicebus @danbugs #770
  - [x]  sdk/core #806
 
After that, we can remove the existing `azure_core::Error` & `azure_core::HttpError` and friends.

Migration is more tedious than difficult. A bunch of `.map_error` can be removed. others can be replaced with `.context(ErrorKind::SomeKind, "some message"`. If a formatted message is useful, then something like:

``` rust
HeaderValue::from_str(&self.header).with_context(
    ErrorKind::DataConversion,
    || {
        format!(
            "user agent '{}' cannot be serialized as an ascii-only HTTP header
            self.header
        )
    },
)?;
```

**Comment by cataggar** [comment]
@mfrw, yes please. I'll have a PR for identity soon that we can review and may be use as an example.

**Comment by johnbatty** [comment]
I've just implemented this for `security_keyvault`, before noticing that it isn't on your list above!
Was this a deliberate omission?

**Comment by johnbatty** [comment]
In your example above for a formatted message, the method should be `with_context(...)` rather than `context` when passing a closure.

**Comment by rickrain** [comment]
@cataggar, I'm interested in helping on the `sdk/storage_blobs`.

**Comment by cataggar** [comment]
@rickrain, I put your name on it.

**Comment by roeap** [comment]
@cataggar - took a stab at `sdk/storage_datalake`.

**Comment by cataggar** [comment]
Thank you everyone!
